spring.application.name=FlightReservationApplication

spring.datasource.url=jdbc:mysql://terraform-b3adad4b2dc00ba55bcd455205.c380gkagcliy.eu-north-1.rds.amazonaws.com:3306/flightdb?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=Redhat123
frontend.url=http://cbz-frontend-project-bucket-flight-reservation-app.s3-website.eu-north-1.amazonaws.com


# Hibernate properties for MySQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.auto-commit=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.address=0.0.0.0